go.property("GROUP", hash(""))

local messages = require("ecs.messages")

function init(self)
	self.enabled = true
end


function on_message(self, message_id, message, sender)
	if message_id == messages.ENABLE_SCRIPT then
		self.enabled = true
	elseif message_id == messages.DISABLE_SCRIPT then
		self.enabled = false
	elseif not self.enabled then
		return
	elseif message_id == messages.CONTACT_POINT_RESPONSE then
		if message.group == self.GROUP then
			go.delete()
		end
	end
end
