go.property("DAMAGE", 1)

local messages = require("ecs.messages")

function init(self)
	self.enabled = true
end

function on_message(self, message_id, message, sender)
	if message_id == messages.ENABLE_SCRIPT then
		self.enabled = true
	elseif message_id == messages.DISABLE_SCRIPT then
		self.enabled = false
	elseif not self.enabled then
		return
	elseif message_id == messages.HIT then
		msg.post(message.other_id, messages.DAMAGE, { amount = self.DAMAGE })
	end
end
